---
title: "تحلیل اشخاص معروف جهانی"
subtitle: "گزارش اولیه"
author: "امین رخشا ۹۵۱۰۹۳۱۵"
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
---
<link rel="stylesheet" type="text/css" href="style.css">

<p class = "persian_header">
مقدمه
</p>

<div class = "persian_normal">
در این پروژه به بررسی شخصیت&zwnj;های معروف جهانی می&zwnj;پردازیم. برای اطلاعات اشخاص از داده&zwnj;ی Pantheon استفاده می&zwnj;کنیم. این داده از ویکیپدیا استخراج شده است و شامل اطلاعات تمام افرادی که صفحه&zwnj;ی  در مورد آن&zwnj;ها به حداقل ۲۵ زبان موجود است می&zwnj;باشد.  این شرط به این معنی است که این&zwnj;ها افرادی هستند که در سطح جهان معروف هستند. اطلاعات حدود ۱۲ هزار نفر از ۳۵۰۰ سال قبل از میلاد تا به امروز که در این شرط صدق می&zwnj;کنند در این داده گردآوری و تمیز شده است. در این گزارش پیشرفت فعلی کار را ارائه می&zwnj;دهیم.
</div>

<p class = "persian_header">
فایل&zwnj;های پروژه
</p>

<div class = "persian_normal">
ساختار فایل&zwnj;های پروژه به شکل زیر است:
</div>

```{r eval = F}
data
|-- pantheon
|-- HA
|-- generated
    |--HA-PAN_linkage.csv
    |--missingCitiesLocations.csv
    |--pantheon_cleaned.csv
reports
|-- firstReport
rscripts
|-- requirements.R
|-- locationFetch.R
|-- data_cleaning.R
|-- HA_linkage.R
|-- locationAnalysis.R
|-- genderAnalaysis.R
output
|-- worldBubbleTimePlot.rds
|-- worldPointPlot.rds
run_all.R
ReadMe.md
.gitignore
DA_project.Rproj
```


<div class = "persian_normal">
data:
در این پوشه داده&zwnj;ها قرار می&zwnj;گیرند. Pantheon و HA (که به آن خواهیم پرداخت)  داده&zwnj;های خام هستند.  پوشه&zwnj;ی generated شامل داده&zwnj;هایی است که از روی داده&zwnj;ی خام یا با اجرای یک کد به دست می&zwnj;آید. 
</div>

<div class = "persian_normal">
rscripts:
دکدها در این پوشه قرار دارند. فایل requirements.R شامل تمام کتابخانه&zwnj;های ضروری برای اجرای کدها است.
</div>

<div class = "persian_normal">
output:
در این پوشه خروجی کدها برای مثال نمودارها قرار داده می&zwnj;شوند. در گزارش&zwnj;ها از این فایل&zwnj;ها استفاده می&zwnj;شود.
</div>

<div class = "persian_normal">
reports:
گزارش&zwnj;ها در این پوشه قرار داده می&zwnj;شوند. گزارش تحلیل هر موضوع در گزارشی جدا قرار خواهد گرفت.
</div>

<div class = "persian_normal">
run_all.R:
این کد تمام کدها را اجرا می&zwnj;کند تا گزارش&zwnj;ها تولید شوند.
</div>

